#!/usr/bin/env python3
"""Fetch select POI categories from Overpass API and merge them into the
bundled `app/src/main/assets/pois-nl.geojson`.

Each entry in `CATEGORY_QUERIES` is a verbatim Overpass QL query — the same
text you would paste into overpass-turbo. The `{{bbox}}` placeholder is
substituted with the project's NL bounding box at request time.

Running this script REPLACES every feature whose `properties.category` matches
a key in `CATEGORY_QUERIES` and re-inserts the freshly fetched ones; all other
categories are kept untouched, so you can iterate on one category at a time.
"""

from __future__ import annotations

import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

# Netherlands bbox used by the Android map (NL_BBOX_SW / NL_BBOX_NE in
# InteractiveMap.kt). Overpass expects the order: south,west,north,east.
NL_BBOX = "50.7,3.3,53.6,7.3"

OVERPASS_URL = "https://overpass-api.de/api/interpreter"

# Verbatim Overpass QL per category. Keep the original wizard comments so it
# stays obvious that the source of truth lives here. Adding a new category is
# as simple as appending to this dict.
CATEGORY_QUERIES: dict[str, str] = {
    "aed": """\
/*
This has been generated by the overpass-turbo wizard.
The original search was:
"AED"
*/
[out:json][timeout:25];
// gather results
node["emergency"="defibrillator"]({{bbox}});
// print results
out geom;
""",
    "hospital": """\
[out:json][timeout:25];
nwr["amenity"="hospital"]({{bbox}});
out center;
""",
}


def fetch_overpass(query: str) -> list[dict]:
    """POST `query` to the Overpass API and return its `elements` list."""
    body = urllib.parse.urlencode({"data": query.replace("{{bbox}}", NL_BBOX)})
    req = urllib.request.Request(
        OVERPASS_URL,
        data=body.encode("utf-8"),
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return payload.get("elements") or []


def element_coords(element: dict) -> tuple[float, float] | None:
    """Return (lon, lat) for an Overpass element regardless of node/way/relation."""
    if "lat" in element and "lon" in element:
        return float(element["lon"]), float(element["lat"])
    center = element.get("center")
    if center and "lat" in center and "lon" in center:
        return float(center["lon"]), float(center["lat"])
    return None


def build_feature(element: dict, category: str) -> dict | None:
    """Convert a single Overpass element into a GeoJSON Point feature.

    Returns None when the element lacks a usable coordinate (boundary
    relations without a center, mostly).
    """
    coords = element_coords(element)
    if coords is None:
        return None
    tags = element.get("tags") or {}
    street = tags.get("addr:street") or ""
    house = tags.get("addr:housenumber") or ""
    line = " ".join(p for p in (street, house) if p).strip()
    city = tags.get("addr:city") or ""
    if line and city:
        addr_full = f"{line}, {city}"
    else:
        addr_full = line or city
    return {
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": list(coords)},
        "properties": {
            "id": f"{element['type']}/{element['id']}",
            "category": category,
            "name": tags.get("name", ""),
            "phone": tags.get("phone", ""),
            "opening_hours": tags.get("opening_hours", ""),
            "wheelchair": tags.get("wheelchair", ""),
            "operator": tags.get("operator", ""),
            "addr_full": addr_full,
        },
    }


def merge_into_geojson(path: Path, fresh: dict[str, list[dict]]) -> None:
    """Replace all features whose category appears in `fresh` with the new ones."""
    data = json.loads(path.read_text())
    keep = [
        f
        for f in (data.get("features") or [])
        if (f.get("properties") or {}).get("category") not in fresh
    ]
    for feats in fresh.values():
        keep.extend(feats)
    data["features"] = keep
    path.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    geojson = root / "app" / "src" / "main" / "assets" / "pois-nl.geojson"
    fresh: dict[str, list[dict]] = {}
    for category, query in CATEGORY_QUERIES.items():
        print(f"Querying Overpass for category={category}\u2026", flush=True)
        elements = fetch_overpass(query)
        feats = [f for f in (build_feature(e, category) for e in elements) if f]
        fresh[category] = feats
        print(f"  {len(feats)} features")
    merge_into_geojson(geojson, fresh)
    total = sum(len(v) for v in fresh.values())
    print(f"Wrote {total} refreshed features into {geojson.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
