#!/usr/bin/env python3
"""
Build app/src/main/assets/tiles/nl.mbtiles from PDOK BRT raster tiles.

Single-purpose: pulls the slippy tile pyramid covering the Netherlands at
z5..z13 from the public PDOK service and assembles them into a standard
MBTiles SQLite file consumed by the app's localhost tile server.

Usage:
    python3 scripts/build_nl_mbtiles.py

Re-running is safe — already-fetched tiles are skipped, partial runs resume.
"""
from __future__ import annotations

import math
import os
import sqlite3
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib import request
from urllib.error import HTTPError, URLError

# Bbox covering all of NL with a small buffer.
LAT_MIN, LAT_MAX = 50.5, 53.7
LON_MIN, LON_MAX = 3.0, 7.5
ZOOM_MIN, ZOOM_MAX = 5, 13

TILE_URL = (
    "https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/"
    "standaard/EPSG:3857/{z}/{x}/{y}.png"
)
USER_AGENT = "EmergencyApp-OfflineTileBuilder/1.0 (+contact: hackathon)"

CONCURRENCY = 16  # be polite to PDOK
MAX_RETRIES = 4

OUT = (
    Path(__file__).resolve().parent.parent
    / "app/src/main/assets/tiles/nl.mbtiles"
)


def deg2num(lat: float, lon: float, z: int) -> tuple[int, int]:
    lat_r = math.radians(lat)
    n = 2**z
    x = int((lon + 180) / 360 * n)
    y = int((1 - math.log(math.tan(lat_r) + 1 / math.cos(lat_r)) / math.pi) / 2 * n)
    return x, y


def init_db(db: sqlite3.Connection) -> None:
    db.executescript(
        """
        CREATE TABLE IF NOT EXISTS metadata (name TEXT, value TEXT);
        CREATE TABLE IF NOT EXISTS tiles (
            zoom_level  INTEGER,
            tile_column INTEGER,
            tile_row    INTEGER,
            tile_data   BLOB
        );
        CREATE UNIQUE INDEX IF NOT EXISTS tile_index
            ON tiles (zoom_level, tile_column, tile_row);
        """
    )
    meta = {
        "name": "nl-pdok-brt",
        "format": "png",
        "minzoom": str(ZOOM_MIN),
        "maxzoom": str(ZOOM_MAX),
        "bounds": f"{LON_MIN},{LAT_MIN},{LON_MAX},{LAT_MAX}",
        "type": "baselayer",
        "version": "1",
        "description": "PDOK BRT Achtergrondkaart, NL coverage",
        "attribution": "© Kadaster",
    }
    for k, v in meta.items():
        db.execute(
            "INSERT INTO metadata (name, value) VALUES (?, ?) "
            "ON CONFLICT DO NOTHING",
            (k, v),
        )
    db.commit()


def existing_keys(db: sqlite3.Connection) -> set[tuple[int, int, int]]:
    return {
        (z, x, y)
        for (z, x, y) in db.execute(
            "SELECT zoom_level, tile_column, tile_row FROM tiles"
        )
    }


def fetch_tile(z: int, x: int, y: int) -> bytes | None:
    url = TILE_URL.format(z=z, x=x, y=y)
    req = request.Request(url, headers={"User-Agent": USER_AGENT})
    for attempt in range(MAX_RETRIES):
        try:
            with request.urlopen(req, timeout=20) as r:
                return r.read()
        except HTTPError as e:
            if e.code == 404:
                return b""  # tile not generated by PDOK; record as empty
            time.sleep(0.5 * (2**attempt))
        except (URLError, TimeoutError):
            time.sleep(0.5 * (2**attempt))
    return None


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(OUT)
    init_db(db)
    have = existing_keys(db)

    work: list[tuple[int, int, int]] = []
    for z in range(ZOOM_MIN, ZOOM_MAX + 1):
        x_min, y_max = deg2num(LAT_MIN, LON_MIN, z)
        x_max, y_min = deg2num(LAT_MAX, LON_MAX, z)
        for x in range(x_min, x_max + 1):
            for y in range(y_min, y_max + 1):
                # MBTiles uses TMS y-axis (flipped from XYZ)
                tms_y = (2**z - 1) - y
                if (z, x, tms_y) in have:
                    continue
                work.append((z, x, y))

    print(f"NL MBTiles: {len(work)} tiles to fetch (existing: {len(have)})")

    completed = 0
    last_log = time.time()
    pending: list[tuple[int, int, int, bytes]] = []

    def flush() -> None:
        if not pending:
            return
        db.executemany(
            "INSERT OR REPLACE INTO tiles "
            "(zoom_level, tile_column, tile_row, tile_data) "
            "VALUES (?, ?, ?, ?)",
            pending,
        )
        db.commit()
        pending.clear()

    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        futures = {ex.submit(fetch_tile, z, x, y): (z, x, y) for z, x, y in work}
        for fut in as_completed(futures):
            z, x, y = futures[fut]
            try:
                data = fut.result()
            except Exception as exc:  # noqa: BLE001
                print(f"[ERR] {z}/{x}/{y}: {exc}", file=sys.stderr)
                continue
            if data is None:
                print(f"[FAIL] {z}/{x}/{y}: gave up after retries", file=sys.stderr)
                continue
            if data:
                tms_y = (2**z - 1) - y
                pending.append((z, x, tms_y, data))
                if len(pending) >= 200:
                    flush()
            completed += 1
            now = time.time()
            if now - last_log > 4:
                pct = 100.0 * completed / max(1, len(work))
                print(f"  {completed}/{len(work)} ({pct:.1f}%)")
                last_log = now

    flush()

    # Final report
    (count,) = db.execute("SELECT COUNT(*) FROM tiles").fetchone()
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"Done — {count} tiles in {OUT} ({size_mb:.1f} MB)")
    db.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
